import os
from pathlib import Path

def get_solution_files():
    """Find all Python, Java, C++, and Rust solution files"""
    base_dir = Path("Leetcode")
    python_files = []
    java_files = []
    cpp_files = []
    rust_files = []

    for py_file in base_dir.rglob("*.py"):
        python_files.append(py_file)
    for java_file in base_dir.rglob("*.java"):
        java_files.append(java_file)
    for cpp_file in base_dir.rglob("*.c++"):
        cpp_files.append(cpp_file)
    for rs_file in base_dir.rglob("*.rs"):
        rust_files.append(rs_file)

    return python_files, java_files, cpp_files, rust_files


def generate_readme(python_files, java_files, cpp_files, rust_files):
    """Generate README content"""
    readme_content = f"""# LeetCode Solutions

![Tests](https://github.com/zigfox123/Leetcode/actions/workflows/test-solutions.yaml/badge.svg)

My solutions to LeetCode problems in Python, Java, C++, and Rust.

## 📊 Statistics

- **Total Solutions:** {len(python_files) + len(java_files) + len(cpp_files) + len(rust_files)}
- **Python Solutions:** {len(python_files)}
- **Java Solutions:** {len(java_files)}
- **C++ Solutions:** {len(cpp_files)}
- **Rust Solutions:** {len(rust_files)}

## 🐍 Python Solutions

"""
    if python_files:
        for file in sorted(python_files):
            problem_name = file.stem.replace("_", " ").replace("-", " ").title()
            readme_content += f"- [{problem_name}]({file})\n"
    else:
        readme_content += "No Python solutions yet.\n"

    readme_content += "\n## ☕ Java Solutions\n\n"
    if java_files:
        for file in sorted(java_files):
            problem_name = file.stem.replace("_", " ").replace("-", " ").title()
            readme_content += f"- [{problem_name}]({file})\n"
    else:
        readme_content += "No Java solutions yet.\n"

    readme_content += "\n## 🇨 C++ Solutions\n\n"
    if cpp_files:
        for file in sorted(cpp_files):
            problem_name = file.stem.replace("_", " ").replace("-", " ").title()
            readme_content += f"- [{problem_name}]({file})\n"
    else:
        readme_content += "No C++ solutions yet.\n"

    readme_content += "\n## 🦀 Rust Solutions\n\n"
    if rust_files:
        for file in sorted(rust_files):
            problem_name = file.stem.replace("_", " ").replace("-", " ").title()
            readme_content += f"- [{problem_name}]({file})\n"
    else:
        readme_content += "No Rust solutions yet.\n"

    readme_content += """
---
*This README is automatically generated by GitHub Actions*
"""
    return readme_content


def main():
    python_files, java_files, cpp_files, rust_files = get_solution_files()
    readme_content = generate_readme(python_files, java_files, cpp_files, rust_files)

    with open("README.md", "w") as f:
        f.write(readme_content)

    print(f"✓ Generated README with {len(python_files)} Python, {len(java_files)} Java, {len(cpp_files)} C++, and {len(rust_files)} Rust solutions")


if __name__ == "__main__":
    main()