import os
from pathlib import Path

def get_solution_files():
    """Find all Python and Java solution files"""
    # Your structure has Leetcode/Leetcode/... so we need to adjust
    base_dir = Path("Leetcode")
    
    python_files = []
    java_files = []
    
    # Find all .py and .java files recursively
    for py_file in base_dir.rglob("*.py"):
        python_files.append(py_file)
    
    for java_file in base_dir.rglob("*.java"):
        java_files.append(java_file)
    
    return python_files, java_files

def generate_readme(python_files, java_files):
    """Generate README content"""
    readme_content = f"""# LeetCode Solutions

![Tests](https://github.com/zigfox123/Leetcode/actions/workflows/test-solutions.yml/badge.svg)

My solutions to LeetCode problems in Python and Java.

## 📊 Statistics

- **Total Solutions:** {len(python_files) + len(java_files)}
- **Python Solutions:** {len(python_files)}
- **Java Solutions:** {len(java_files)}

## 🐍 Python Solutions

"""
    
    if python_files:
        for file in sorted(python_files):
            problem_name = file.stem.replace("_", " ").replace("-", " ").title()
            readme_content += f"- [{problem_name}]({file})\n"
    else:
        readme_content += "No Python solutions yet.\n"
    
    readme_content += "\n## ☕ Java Solutions\n\n"
    
    if java_files:
        for file in sorted(java_files):
            problem_name = file.stem.replace("_", " ").replace("-", " ").title()
            readme_content += f"- [{problem_name}]({file})\n"
    else:
        readme_content += "No Java solutions yet.\n"
    
    readme_content += """
---

*This README is automatically generated by GitHub Actions*
"""
    
    return readme_content

def main():
    python_files, java_files = get_solution_files()
    readme_content = generate_readme(python_files, java_files)
    
    with open("README.md", "w") as f:
        f.write(readme_content)
    
    print(f"✓ Generated README with {len(python_files)} Python and {len(java_files)} Java solutions")

if __name__ == "__main__":
    main()